# Generated by Django 4.2.2 on 2023-08-14 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_blogpost_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='mainedits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_of_the_site', models.CharField(default='', max_length=200, unique=True)),
                ('site_image', models.ImageField(default='', upload_to='image/')),
            ],
        ),
    ]
