# Generated by Django 4.2.2 on 2023-08-14 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_mainedits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainedits',
            name='site_image',
            field=models.ImageField(default='', upload_to='images/'),
        ),
    ]
